# Generated by Django 5.2.5 on 2026-01-31 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dentist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('specialization', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('GENERAL', 'General / Consultation'), ('ENDO', 'Endodontics'), ('EXTRACTION', 'Tooth Extraction'), ('IMPLANT', 'Implants'), ('WHITENING', 'Whitening / Bleaching'), ('RESTORATION', 'Restoration'), ('SURGERY', 'Surgery'), ('REMOVABLE_ARCH', 'Removable Prosthodontics (per arch)'), ('COMPLETE_DENTURE', 'Complete Denture'), ('THERMOSENS', 'Thermosens'), ('IVOCAP', 'Ivocap'), ('REMOVABLE_WHITE', 'Removable Prostho (White Plastic)'), ('RPD_METAL', 'RPD Metal Framework'), ('ORTHO', 'Orthodontics'), ('FIXED', 'Fixed Prosthodontics'), ('DENTURE_REPAIR', 'Denture Repair')], default='GENERAL', max_length=50)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dentist_name', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('preferred_time', models.TimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('not_arrived', 'Not Yet Arrived'), ('arrived', 'Arrived'), ('ongoing', 'On Going'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='not_arrived', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='appointment.branch')),
                ('dentist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='appointment.dentist')),
                ('services', models.ManyToManyField(related_name='appointments', to='appointment.service')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('status_changed', 'Status Changed'), ('cancelled', 'Cancelled')], max_length=50)),
                ('old_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_status', models.CharField(blank=True, max_length=20, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_logs', to=settings.AUTH_USER_MODEL)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='appointment.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='DentistAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dentist_availabilities', to='appointment.branch')),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='appointment.dentist')),
            ],
        ),
        migrations.CreateModel(
            name='DentistService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dentist_services', to='appointment.dentist')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_dentists', to='appointment.service')),
            ],
        ),
    ]
