# Generated by Django 5.2.5 on 2026-01-31 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField()),
                ('telephone', models.CharField(max_length=11)),
                ('age', models.PositiveIntegerField()),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('is_guest', models.BooleanField(default=False)),
                ('guest_id', models.CharField(blank=True, max_length=50, null=True)),
                ('particular_condition', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('allergy', models.CharField(blank=True, max_length=255, null=True)),
                ('pregnancy_status', models.CharField(blank=True, max_length=255, null=True)),
                ('medications', models.TextField(blank=True, null=True)),
                ('abnormal_bleeding_history', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Odontogram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tooth_number', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('dentist', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('service', models.ManyToManyField(blank=True, to='appointment.service')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odontograms', to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('dentist', models.CharField(max_length=200)),
                ('services', models.TextField(blank=True, default='')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('findings', models.TextField()),
                ('prescriptions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to='patient.patient')),
            ],
            options={
                'verbose_name': 'Treatment History',
                'verbose_name_plural': 'Treatment Histories',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bill_type', models.CharField(default='', max_length=100)),
                ('payment_mode', models.CharField(default='Cash', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_bill', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_history', to='patient.patient')),
            ],
            options={
                'verbose_name': 'Billing History',
                'verbose_name_plural': 'Billing Histories',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Xray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='xrays/')),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xrays', to='patient.patient')),
            ],
        ),
    ]
